#ifndef LIB_SYS_SYSCALL_H
#define LIB_SYS_SYSCALL_H
enum {  // --- Syscall numbers ---
    SYS_read   = 0,
    SYS_write  = 1,
    SYS_open   = 2,
    SYS_close  = 3,
    SYS_newstat = 4,
    SYS_newfstat = 5,
    SYS_newlstat = 6,
    SYS_lseek  = 8,
    SYS_mmap   = 9,
    SYS_munmap = 11,
    SYS_brk    = 12,
    SYS_ioctl  = 16,
    SYS_access = 21,
    SYS_pipe   = 22,
    SYS_dup    = 32,
    SYS_dup2   = 33,
    SYS_fork   = 57,
    SYS_execve = 59,
    SYS_exit   = 60,
    SYS_wait4  = 61,
    SYS_getcwd = 79,
    SYS_chdir  = 80,
    SYS_rename = 82,
    SYS_mkdir  = 83,
    SYS_rmdir  = 84,
    SYS_creat  = 85,
    SYS_chmod  = 90,
    SYS_chown  = 92,
    SYS_gettimeofday = 96,
    SYS_clock_gettime = 228,
};
#endif
